name: Release Zip
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip extension folder
        run: |
          cd extension
          zip -r ../extension.zip .
      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip